PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX sh: <http://www.w3.org/ns/shacl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

CONSTRUCT {
  ?class a rdfs:Class, ?classType ;
    rdfs:label ?classLabel ;
    owl:equivalentClass ?classEquivalent .
}
WHERE {
# GRAPH <http://orkg.org/orkg/> {
    [] a ?class .
    optional {
      ?class a ?classType .
    }
    optional {
      ?class rdfs:label ?classLabel .
    }
    optional {
      ?class owl:equivalentClass ?classEquivalent .
    }
# }
}
